---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


# projak

<!-- badges: start -->
<!-- badges: end -->

The goal of projak is to make an R package that can generate the projection module in `RTMB`

## Installation

You can install the development version of projak from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("BenWilliams-NOAA/projak")
```

## Example

This is a basic example which shows you how to solve a common problem:

``` r
library(projak)
# pull in results from a RTMB assessment
rpt = projak::m22.1 # 2024 goa northern rockfish assessment results - 2024 catch data was incomplete
result = run_projections(rpt, future_catch = c("2024" = 1170.036), yield_ratio = rpt$yield_ratio)
format_output(result, var = "catch")
format_output(result, var = "f")
format_output(result, var = "ssb")
```

Alternatively, any model could be made to work with this by simply grabbing the outputs and placing them in a named list.

``` r
rpt <- list(
  years = 1977:2024,
  ages = list(2),
  Nat = my_abundance_matrix, 
  M = 0.06,
  waa = c(0.1, 0.5, 0.8, ...),
  maa = c(0.0, 0.01, 0.1, ...),
  slx = my_selectivity_matrix,
  spawn_fract = 0.25,
  recruits = my_historical_rec_vector,
  log_mean_R = 1.5,
  sigmaR = 0.5,
  F40 = 0.08,
  B40 = 25000,
  F35 = 0.10,
  B35 = 21000,
  Ft = my_historical_f_vector,
  yield_ratio = 0.94
)

```

# Disclaimer

This repository is a scientific product and is not official communication of the National Oceanic and Atmospheric Administration, or the United States Department of Commerce. 
All NOAA GitHub project content is provided on an "as is" basis and the user assumes responsibility for its use. 
Any claims against the Department of Commerce or Department of Commerce bureaus stemming from the use of this GitHub project will be governed by all applicable Federal law. 
Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. 
The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.



